### ISSUE TITLE
Problem opening the kicad rev2 project

### ISSUE THREAD

**Issue by FacepalmMute** [twlostow/dsi-shield#7]
Hey twlostow,

there are some problems when i try to open your rev2 kicad project.

1: Opening the .sch file gives me a dialog which says that some library's missing in /mnt/big/CernLib/KiCad/SchLib/... . Which library's do you use?

2: By opening the pcb file i get an error which says that my kicad version is to old, which is not the case. (newest 4.0.7+dfsg1-1)

**Comment by twlostow** [comment]
1) these are my own libraries, not published yet. Using the rescue option
you can read the full schematic

2) open it in a nightly build

Tom

2017-10-01 13:17 GMT+02:00 Nikita Schewtschuk <notifications@github.com>:

**Comment by Burnwhite** [comment]
I am a student and I want to make one by myself but I encountered some problems.
1. When I download them from github and open .xise on ise14.7 from win10, lots of ".v" files are missing. How can I solve that?
2. Every time I run the .xise file, it would be an error: 989 tells me "failed to process the bmm file". How can I solve this?
Could you please send me a complete project without any missing files through email? my email is: l.zongyao.1@research.gla.ac.uk

Thank you so much if you can see this issues and reply.
